[package]
name = "kafka-settings"
version = "0.3.1"
authors = ["Sebastian Rollen <seb@overmu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = "0.26"
serde = "1.0"

[dev-dependencies]
config = "0.11.0"
